### ISSUE TITLE
During npm-install, gulp build fails

### ISSUE THREAD

**Issue by chadfurman** [niftylettuce/gulp-aws-splash#5]
lotus@InfiniteDesktop:~/code/penspire$ gulp build
module.js:339
    throw err;
    ^

Error: Cannot find module './pipeline'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/www/penspire/node_modules/gulp-live-server/node_modules/tiny-lr/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:4:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by chadfurman** [comment]
rm -rf on node_modules and then reinstalling seems to have removed this error
